const defs=[
{name:"Battery",icon:"🔋",desc:"Power source for the experiment."},
{name:"Switch",icon:"🔘",desc:"Controls whether power can pass."},
{name:"Motor",icon:"⚙️",desc:"Converts electrical energy into motion."},
{name:"Light",icon:"💡",desc:"Turns on when a powered circuit reaches it."},
{name:"Sensor",icon:"📡",desc:"Detects a simulated trigger."},
{name:"Magnet",icon:"🧲",desc:"A field component for future experiments."},
{name:"Timer",icon:"⏱️",desc:"Delays or sequences a machine action."},
{name:"Speaker",icon:"🔊",desc:"Produces a simulated sound output."}
];
const components=document.getElementById("components"),lab=document.getElementById("lab"),count=document.getElementById("partCount"),eventText=document.getElementById("eventText"),statusText=document.getElementById("statusText"),runDot=document.getElementById("runDot"),insEmpty=document.getElementById("inspectorEmpty"),insBody=document.getElementById("inspectorBody");
let nodes=[],connections=[],selected=null,nextId=1;
defs.forEach((d,i)=>{const b=document.createElement("button");b.className="component";b.innerHTML='<span class="ci">'+d.icon+'</span><span><b>'+d.name+'</b><small>'+d.desc.split(".")[0]+'</small></span>';b.addEventListener("click",()=>place(d));components.appendChild(b)});
function place(d){const node={id:nextId++,...d,x:60+(nodes.length%4)*135,y:55+(Math.floor(nodes.length/4)%3)*105};nodes.push(node);select(node.id);render();say(d.name+" placed in the lab.");}
function render(){lab.querySelectorAll(".node,.connection").forEach(e=>e.remove());nodes.forEach(n=>{const e=document.createElement("div");e.className="node"+(selected===n.id?" selected":"");e.style.left=n.x+"px";e.style.top=n.y+"px";e.innerHTML='<span class="node-icon">'+n.icon+'</span><strong>'+n.name+'</strong><small>ID N-'+String(n.id).padStart(2,"0")+'</small>';e.addEventListener("click",()=>select(n.id));lab.appendChild(e)});connections.forEach(c=>{const a=nodes.find(n=>n.id===c.a),b=nodes.find(n=>n.id===c.b);if(!a||!b)return;const line=document.createElement("div");line.className="connection";const x1=a.x+50,y1=a.y+35,x2=b.x+50,y2=b.y+35,dx=x2-x1,dy=y2-y1;line.style.left=x1+"px";line.style.top=y1+"px";line.style.width=Math.hypot(dx,dy)+"px";line.style.transform="rotate("+Math.atan2(dy,dx)+"rad)";lab.appendChild(line)});count.textContent=nodes.length;document.getElementById("labMessage").style.display=nodes.length?"none":"grid";document.getElementById("connectionText").textContent=connections.length?connections.length+" connection"+(connections.length===1?"":"s")+" ready":"No connections yet";}
function select(id){selected=id;const n=nodes.find(x=>x.id===id);if(!n)return;insEmpty.hidden=true;insBody.hidden=false;document.getElementById("selectedIcon").textContent=n.icon;document.getElementById("selectedName").textContent=n.name;document.getElementById("selectedDesc").textContent=n.desc;document.getElementById("selectedId").value="N-"+String(n.id).padStart(2,"0");render()}
document.getElementById("connectBtn").addEventListener("click",()=>{if(!selected){say("Select a component first.");return}const candidates=nodes.filter(n=>n.id!==selected);if(!candidates.length){say("Add another component first.");return}const target=candidates[candidates.length-1];if(connections.some(c=>(c.a===selected&&c.b===target.id)||(c.b===selected&&c.a===target.id))){say("Those components are already connected.");return}connections.push({a:selected,b:target.id});render();say("Connected "+nodes.find(n=>n.id===selected).name+" → "+target.name+".")});
document.getElementById("deleteBtn").addEventListener("click",()=>{if(!selected)return;nodes=nodes.filter(n=>n.id!==selected);connections=connections.filter(c=>c.a!==selected&&c.b!==selected);selected=null;insEmpty.hidden=false;insBody.hidden=true;render();say("Component removed.");});
document.getElementById("clearBtn").addEventListener("click",()=>{nodes=[];connections=[];selected=null;insEmpty.hidden=false;insBody.hidden=true;lab.classList.remove("success");render();say("Lab cleared.");});
document.getElementById("runBtn").addEventListener("click",run);
function run(){if(!nodes.length){say("Nothing to run. Add components first.");return}lab.classList.add("running");lab.classList.remove("success");statusText.textContent="RUNNING";runDot.style.background="var(--accent2)";say("Simulation started...");setTimeout(()=>{const names=nodes.map(n=>n.name),powered=names.includes("Battery")&&connections.length>0,light=names.includes("Light")&&powered, motor=names.includes("Motor")&&powered;lab.classList.remove("running");lab.classList.toggle("success",powered);statusText.textContent=light?"OUTPUT ACTIVE":powered?"SIMULATION OK":"NO POWER PATH";runDot.style.background=light?"var(--accent)":"var(--accent2)";say(light?"Success! Power reached the Light. 💡":motor?"Motor has a power path. ⚙️":powered?"Components are connected and powered.":"Add a Battery and connect your components to create a power path.");},1100)}
function say(t){eventText.textContent=t}
render();